### ISSUE TITLE
文档打不开

### ISSUE THREAD

**Issue by shang-yin** [okex/okexchain-go-sdk#92]
## Summary of Bug
https://okchain-docs.readthedocs.io/zh_CN/latest/api/sdk/go-sdk.html

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by RevelationOfTuring** [comment]
你好@shang-yin ，感谢提供问题反馈。

现在地址链接已改为：https://okexchain-docs.readthedocs.io/en/latest/api/sdk/go-sdk.html
